### ISSUE TITLE
Unable to render successfully

### ISSUE THREAD

**Issue by Andy-AO** [joethei/obsidian-local-plantuml#1]
my path is `C:\Users\Andy\scoop\apps\PlantUML\current\plantuml.jar`

![](https://cdn.jsdelivr.net/gh/Andy-AO/GitHubPictureBed/img/20211214131424.png)

**Comment by joethei** [comment]
Which version of plantuml & Java are you running?
Are you able to render the diagram from the command line?

**Comment by Andy-AO** [comment]
> Which version of plantuml & Java are you running? Are you able to render the diagram from the command line?

yes, I can running it.`PlantUML test.puml` can get png file.

`PlantUML 1.2021.16`

```PowerShell
PS>java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

**Comment by joethei** [comment]
I have pushed an update which might fix this issue, or at the very least give some more information as to why this issue happens.

**Comment by Andy-AO** [comment]
The problem remains

![image](https://user-images.githubusercontent.com/38101170/145965757-bcdfde90-8020-47ef-b21e-4c0f1f21f560.png)

**Comment by joethei** [comment]
Could you check with the new version off the main plugin, could not push the update previously

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/145977572-bb556975-c8c5-4f28-acc4-2e5e39bea9cd.png)

**Comment by joethei** [comment]
could you check if it works if you use the svg renderer `plantuml-svg`?
seems like I forgot to fix the error in the png renderer

**Comment by Andy-AO** [comment]
I'm a novice.
Can you provide more information?

**Comment by joethei** [comment]
change the `plantuml` at the start of your diagram to a `plantuml-svg`

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/145986536-039259d6-baa0-4c6c-aaf8-1132459f0c13.png)

**Comment by joethei** [comment]
could you try it now, this time the error should at least be more concrete.

**Comment by Andy-AO** [comment]
> could you try it now, this time the error should at least be more concrete.

`plantuml-svg` can render, but `plantuml` can not yet.

![image](https://user-images.githubusercontent.com/38101170/146075667-87f77239-2b0f-44d7-9c46-0da14b5cf653.png)

**Comment by Andy-AO** [comment]
> While you can decrease the debounce time to get your diagrams faster, local rendering is still slower than rendering using the server.
> 
> While there are methods to make this faster, either:
> 
> * they don't work in the context of an obsidian plugin
> * or don't support some specific diagram type/output format

Originally, I thought I could achieve the level of IDEA. Now it seems very difficult
